services:
  - type: web
    name: sewasetu-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    domains:
      - api.sarojkumarayer.com.np
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_SECURE
        value: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        value: "SewaSetu Support" <sewasetu@gmail.com>
      - key: GEMINI_API_KEY
        sync: false
